### ISSUE TITLE
[BUG] Hitting "I have reached my destination" finishes the trip without successful answer from the server

### ISSUE THREAD

**Issue by FredFS** [AMOS-2015/amos-ss15-proj2#14]
Even if I have no internet connection I can press "I have reached my destination" button and I get redirected to the join trip view and cannot access my trip anymore though the server still thinks that I am in the car. Client should wait for a successful server answer before redirecting the client.

**Comment by Webbed90** [comment]
In product backlog as "B42 - [BUG] Hitting "I have reached my destination" finishes the trip without successful answer from the server "
