### ISSUE TITLE
[BUG] "O no your trip has been cancelled" notification redirects to the wrong screen

### ISSUE THREAD

**Issue by FredFS** [AMOS-2015/amos-ss15-proj2#15]
Clicking on the notification that appears for the passenger if the driver cancels the trip brings the passengers(!!) to the "My Trip Requests" screen that should not even exist for the passenger.

**Comment by Webbed90** [comment]
In Product Backlog as "B43 - [BUG] "O no your trip has been cancelled" notification redirects to the wrong screen"
