### ISSUE TITLE
[Bug] Same passenger can join a trip multiple times

### ISSUE THREAD

**Issue by VanessaLange** [AMOS-2015/amos-ss15-proj2#2]
If, for some reason, there is an inconsistent state on the client (see bug #1 for example) which enables a passenger to join a trip although he has already joined one, he can join the same trip multiple times. The server does not prevent this from happening.

**Comment by Webbed90** [comment]
Added to Product Backlog as "B22 - [BUG] passenger can join multiple trips at same time"

**Comment by Maddoc42** [comment]
Side note: joining a trip multiple times might even be considered a feature, although not at the same time. So sequential joining is ok (?), parallel not.
