### ISSUE TITLE
[BUG] Cancel Trip does not always work

### ISSUE THREAD

**Issue by FredFS** [AMOS-2015/amos-ss15-proj2#8]
Sometimes it happens that the trip will not be cancelled for the driver, though the passenger hits cancel and his screen changes (no possibility to cancel again). The state is not even changed on the server. So if the driver cancels the trip the passenger will be informed that the trip was cancelled (though he should not be part of the trip anymore).

**Comment by Webbed90** [comment]
Added to Product Backlog as "B35 - [BUG] Passenger cancel trip not working reliably"
